<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '\'{class}\' must extend from \'yii\\rbac\\Rule\' or its child class' => '\'{class}\' must extend from \'yii\\rbac\\Rule\' or its child class',
    'Action' => 'Action',
    'Are you sure to delete this item?' => 'Are you sure to delete this item?',
    'Assign' => 'Asignar',
    'Assignment : {0}' => 'Asignacion : {0}',
    'Assignments' => 'Asignaciones',
    'Class Name' => 'Nombre de la clase',
    'Create' => 'Crear',
    'Create Rule' => 'Crear Regla',
    'Create Role' => 'Crear Rol',
    'Data' => 'Dato',
    'Delete' => 'Borrar',
    'Description' => 'Descripcion',
    'Invalid rule "{value}"' => 'Regla invalida "{value}"',
    'Item has been removed.' => 'Item has been removed.',
    'Item has been saved.' => 'Item has been saved.',
    'Name' => 'Nombre',
    'Permissions' => 'Permisos',
    'Refresh' => 'Refrescar',
    'Remove' => 'Remover',
    'Roles' => 'Roles',
    'Role : {0}' => 'Role : {0}',
    'Permission : {0}' => 'Permisos : {0}',
    'Create Permission' => 'Crear Permiso',
    'Routes' => 'Rutas',
    'Rule' => 'Regla',
    'Rule "{value}" does not exists' => 'Rule "{value}" does not exists',
    'Rule : {0}' => 'Regla : {0}',
    'Rule Name' => 'Nombre de Regla',
    'Rule has been deleted.' => 'Rule has been deleted.',
    'Rule has been saved.' => 'Rule has been saved.',
    'Rules' => 'Reglas',
    'Search for assigned' => 'Buscar asignado',
    'Search for available' => 'Buscar disponible',
    'The requested page does not exist.' => 'The requested page does not exist.',
    'Type' => 'Tipo',
    'Unknown class \'{class}\'' => 'Unknown class \'{class}\'',
    'Update' => 'Actualizar',
    'Update Rule : {0}' => 'Actualizar regla : {0}',
    'Update Role : {0}' => 'Actualizar Rol : {0}',
    'Update Permission : {0}' => 'Actualizar permiso : {0}',
    'users' =>'Usuarios',
    'Select Rule' => 'Select Rule',
];
